# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marca', models.CharField(max_length=150)),
                ('Type', models.TextField()),
                ('Year', models.CharField(max_length=150)),
                ('Colour', models.CharField(max_length=150)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
